name: green_it
description: An application to test sustainability in terms of CO2 emissions

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  sliding_up_panel: ^2.0.0+1
  geolocator: ^9.0.2
  injectable: ^2.1.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  material_floating_search_bar: ^0.3.7
  retrofit: ^4.0.1
  dio: ^5.1.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_map_marker_cluster: ^1.1.1
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.6
  build_runner: ^2.4.4
  retrofit_generator: ^7.0.1
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
